language: node_js

node_js: 0.10

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect: true

before_install:
  - npm install -g gulp bower
  - bower install

script:
  - gulp test:e2e --os=mac
  - gulp test:e2e --os=windows
